ARG BASE=ubuntu:24.04
FROM $BASE
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        g++ cmake ninja-build qt6-base-dev libgl1-mesa-dev qt6-wayland fonts-dejavu-core \
        qt6-image-formats-plugins qt6-svg-plugins libfontconfig-dev \
        ca-certificates dpkg-dev file fakeroot \
    && rm -rf /var/lib/apt/lists/*
